#!/bin/bash

source ./Display
source ./Methods


divider="|-------------------------------------------------|"
lineFormat="|%14s %-34s|\n"


DisplayMainMenu()
{
   clear
   echo $divider
   printf "$lineFormat" "" "Home Options Menu"
   echo $divider
   printf "$lineFormat" "" "1 - File Methods"
   printf "$lineFormat" "" "2 - File Display"
   echo $divider
   printf "|%12s %-36s|\n" "" "0 - Close the Program"
   echo $divider
   echo ""

   GetUserChoice
}


GetUserChoice()
{
   while :
   do
      read -p "Enter your choice: " userOption
 
      case $userOption in
         0) 
            ExitProgram ;;
         1) 
            DisplayMethodsMenu
            ;;
         2) 
            DisplayOptionsMenu
            ;;
         *) 
            ShowErrorMessage "Invalid choice. Please select an option between 0 and 2." 
	    continue ;;
      esac
      break
   done

   sleep 1
   DisplayMainMenu
}


ExitProgram()
{
   echo -n "Closing"
   for i in {1..3}
   do
      echo -n "."
      sleep 0.5
   done
   echo ""
   clear
   exit
} 


ShowErrorMessage()
{
   local message=$1
 
   # Bold ; Red font
   echo -e "\033[1;31m$message \033[0m"

   stty -echo
   sleep 2
   stty echo
 
   while read -t 0.1 -n 1000; do : ; done
 
   echo -e "\033[2A\033[J"
   echo -e "\033[2A"
}


DisplayMainMenu 
